export const O41_PROPS = {
  USER: {
    user_id: 'user.user_id',
    display_name: 'user.display_name',
    team_name: 'user.metadata.team_name',
    avatar: 'user.metadata.avatar',
  },
  MATCHUP: {
    roster_id: 'matchup.roster_id',
    matchup_id: 'matchup.matchup_id',
    points: 'matchup.points',
    starters: 'matchup.starters',
    players: 'matchup.players',
    starters_points: 'matchup.starters_points',
    players_points: 'matchup.players_points',
  },
  ROSTER: {
    owner_id: 'roster.owner_id',
    roster_id: 'roster.roster_id',
    players: 'roster.players',
    starters: 'roster.starters',
    reserve: 'roster.reserve',
    taxi: 'roster.taxi',
    settings: 'roster.settings',
  },
  LEAGUE: {
    league_id: 'league.league_id',
    name: 'league.name',
    avatar: 'league.avatar',
    season: 'league.season',
    total_rosters: 'league.total_rosters',
    scoring_settings: 'league.scoring_settings',
    roster_positions: 'league.roster_positions',
    division_1: 'league.metadata.division_1',
    division_2: 'league.metadata.division_2',
    latest_league_winner_roster_id: 'league.metadata.latest_league_winner_roster_id',
  },
};
